// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skills} from '../models';
import {main} from '../models';
import {team} from '../models';
import {sync} from '../models';


export function AddDirectory(arg1:string):Promise<void>;

export function AddPeerByID(arg1:string,arg2:string):Promise<void>;

export function AddProject(arg1:string,arg2:string):Promise<skills.Project>;

export function AddRecent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddToCollection(arg1:string,arg2:string):Promise<void>;

export function AddToSyncManifest(arg1:Array<string>):Promise<void>;

export function BrowseMarketplace(arg1:string):Promise<Array<skills.MarketplaceSkill>>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearRecent():Promise<void>;

export function ConnectTeam(arg1:string,arg2:string):Promise<team.TeamState>;

export function CreateCollection(arg1:string):Promise<skills.Collection>;

export function CreateFromTemplate(arg1:string,arg2:string,arg3:string):Promise<skills.Skill>;

export function CreateSkill(arg1:string,arg2:skills.ToolType,arg3:string):Promise<skills.Skill>;


export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DisableSkill(arg1:string,arg2:string):Promise<void>;

export function DisableSkillsForTool(arg1:string):Promise<number>;

export function DisconnectTeam():Promise<void>;

export function DuplicateSkill(arg1:string):Promise<skills.Skill>;

export function EnableAllDisabledForTool(arg1:string):Promise<number>;

export function EnableSkill(arg1:string):Promise<void>;

export function GetCollections():Promise<Array<skills.Collection>>;

export function GetDefaultFilename(arg1:skills.ToolType):Promise<string>;

export function GetDefaultScanPaths():Promise<Record<string, Array<string>>>;

export function GetDefaultSubdir(arg1:skills.ToolType):Promise<string>;

export function GetExtraDirs():Promise<Array<string>>;

export function GetDeviceID():Promise<string>;

export function GetFullPeerID():Promise<string>;

export function GetKnownTools():Promise<Array<skills.ToolMeta>>;


export function GetMCPConfigs():Promise<Array<skills.MCPToolConfig>>;

export function GetMarketplaceSources():Promise<Array<skills.MarketplaceSource>>;

export function GetPeers():Promise<Array<sync.PeerInfo>>;

export function GetPlugins():Promise<Array<skills.PluginToolConfig>>;

export function GetProjectOverrides(arg1:string):Promise<Array<string>>;

export function GetRecent():Promise<skills.RecentStore>;

export function GetSettings():Promise<skills.Settings>;

export function GetSkills():Promise<Array<skills.Skill>>;

export function GetSyncConflicts():Promise<any>;

export function GetSyncManifest():Promise<any>;

export function GetSyncStatus():Promise<Record<string, any>>;

export function GetTeamManagedPaths():Promise<Array<string>>;

export function GetTeamState():Promise<team.TeamState>;

export function GetTemplates():Promise<Array<skills.SkillTemplate>>;

export function GetVersion():Promise<string>;

export function Hide():Promise<void>;

export function InstallMarketplaceSkill(arg1:string,arg2:string,arg3:string):Promise<string>;

export function IsSkillDisabled(arg1:string):Promise<boolean>;

export function IsTeamManaged(arg1:string):Promise<boolean>;

export function ListDisabledSkills():Promise<Array<skills.DisabledSkillInfo>>;

export function ListProjects():Promise<Array<skills.Project>>;

export function OpenURL(arg1:string):Promise<void>;

export function PreviewMarketplaceSkill(arg1:string):Promise<string>;

export function ReadSkillFile(arg1:string):Promise<main.ReadSkillFileResult>;

export function RemoveDirectory(arg1:string):Promise<void>;

export function RemoveFromCollection(arg1:string,arg2:string):Promise<void>;

export function RemoveFromSyncManifest(arg1:Array<string>):Promise<void>;

export function RemovePeerByID(arg1:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function ResolveSyncConflict(arg1:string,arg2:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SaveSettings(arg1:skills.Settings):Promise<void>;

export function SaveSkill(arg1:string,arg2:string):Promise<void>;

export function ScanProjectSkills(arg1:string):Promise<Array<skills.Skill>>;

export function SearchSkills(arg1:string):Promise<Array<skills.SearchResult>>;

export function SelectDirectory():Promise<string>;

export function SelectDirectoryForTool():Promise<string>;

export function SelectProjectDirectory():Promise<string>;

export function SetProjectSkillOverride(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Show():Promise<void>;

export function SyncFiles(arg1:Array<string>):Promise<void>;

export function TeamSyncNow():Promise<void>;

export function UpdateSkillMetadata(arg1:string,arg2:Record<string, string>):Promise<void>;

export function ValidateSkills():Promise<Record<string, Array<skills.ValidationWarning>>>;
