// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirectory(arg1) {
  return window['go']['main']['App']['AddDirectory'](arg1);
}

export function AddPeerByID(arg1, arg2) {
  return window['go']['main']['App']['AddPeerByID'](arg1, arg2);
}

export function AddProject(arg1, arg2) {
  return window['go']['main']['App']['AddProject'](arg1, arg2);
}

export function AddRecent(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRecent'](arg1, arg2, arg3);
}

export function AddToCollection(arg1, arg2) {
  return window['go']['main']['App']['AddToCollection'](arg1, arg2);
}

export function AddToSyncManifest(arg1) {
  return window['go']['main']['App']['AddToSyncManifest'](arg1);
}

export function BrowseMarketplace(arg1) {
  return window['go']['main']['App']['BrowseMarketplace'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearRecent() {
  return window['go']['main']['App']['ClearRecent']();
}

export function ConnectTeam(arg1, arg2) {
  return window['go']['main']['App']['ConnectTeam'](arg1, arg2);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateFromTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFromTemplate'](arg1, arg2, arg3);
}

export function CreateSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSkill'](arg1, arg2, arg3);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DisableSkill(arg1, arg2) {
  return window['go']['main']['App']['DisableSkill'](arg1, arg2);
}

export function DisableSkillsForTool(arg1) {
  return window['go']['main']['App']['DisableSkillsForTool'](arg1);
}

export function DisconnectTeam() {
  return window['go']['main']['App']['DisconnectTeam']();
}

export function DuplicateSkill(arg1) {
  return window['go']['main']['App']['DuplicateSkill'](arg1);
}

export function EnableAllDisabledForTool(arg1) {
  return window['go']['main']['App']['EnableAllDisabledForTool'](arg1);
}

export function EnableSkill(arg1) {
  return window['go']['main']['App']['EnableSkill'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetDefaultFilename(arg1) {
  return window['go']['main']['App']['GetDefaultFilename'](arg1);
}

export function GetDefaultScanPaths() {
  return window['go']['main']['App']['GetDefaultScanPaths']();
}

export function GetDefaultSubdir(arg1) {
  return window['go']['main']['App']['GetDefaultSubdir'](arg1);
}

export function GetDeviceID() {
  return window['go']['main']['App']['GetDeviceID']();
}

export function GetExtraDirs() {
  return window['go']['main']['App']['GetExtraDirs']();
}

export function GetFullPeerID() {
  return window['go']['main']['App']['GetFullPeerID']();
}

export function GetKnownTools() {
  return window['go']['main']['App']['GetKnownTools']();
}

export function GetMCPConfigs() {
  return window['go']['main']['App']['GetMCPConfigs']();
}

export function GetMarketplaceSources() {
  return window['go']['main']['App']['GetMarketplaceSources']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetProjectOverrides(arg1) {
  return window['go']['main']['App']['GetProjectOverrides'](arg1);
}

export function GetRecent() {
  return window['go']['main']['App']['GetRecent']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetSyncConflicts() {
  return window['go']['main']['App']['GetSyncConflicts']();
}

export function GetSyncManifest() {
  return window['go']['main']['App']['GetSyncManifest']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetTeamManagedPaths() {
  return window['go']['main']['App']['GetTeamManagedPaths']();
}

export function GetTeamState() {
  return window['go']['main']['App']['GetTeamState']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function InstallMarketplaceSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallMarketplaceSkill'](arg1, arg2, arg3);
}

export function IsSkillDisabled(arg1) {
  return window['go']['main']['App']['IsSkillDisabled'](arg1);
}

export function IsTeamManaged(arg1) {
  return window['go']['main']['App']['IsTeamManaged'](arg1);
}

export function ListDisabledSkills() {
  return window['go']['main']['App']['ListDisabledSkills']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PreviewMarketplaceSkill(arg1) {
  return window['go']['main']['App']['PreviewMarketplaceSkill'](arg1);
}

export function ReadSkillFile(arg1) {
  return window['go']['main']['App']['ReadSkillFile'](arg1);
}

export function RemoveDirectory(arg1) {
  return window['go']['main']['App']['RemoveDirectory'](arg1);
}

export function RemoveFromCollection(arg1, arg2) {
  return window['go']['main']['App']['RemoveFromCollection'](arg1, arg2);
}

export function RemoveFromSyncManifest(arg1) {
  return window['go']['main']['App']['RemoveFromSyncManifest'](arg1);
}

export function RemovePeerByID(arg1) {
  return window['go']['main']['App']['RemovePeerByID'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function ResolveSyncConflict(arg1, arg2) {
  return window['go']['main']['App']['ResolveSyncConflict'](arg1, arg2);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSkill(arg1, arg2) {
  return window['go']['main']['App']['SaveSkill'](arg1, arg2);
}

export function ScanProjectSkills(arg1) {
  return window['go']['main']['App']['ScanProjectSkills'](arg1);
}

export function SearchSkills(arg1) {
  return window['go']['main']['App']['SearchSkills'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectDirectoryForTool() {
  return window['go']['main']['App']['SelectDirectoryForTool']();
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function SetProjectSkillOverride(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProjectSkillOverride'](arg1, arg2, arg3);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function SyncFiles(arg1) {
  return window['go']['main']['App']['SyncFiles'](arg1);
}

export function TeamSyncNow() {
  return window['go']['main']['App']['TeamSyncNow']();
}

export function UpdateSkillMetadata(arg1, arg2) {
  return window['go']['main']['App']['UpdateSkillMetadata'](arg1, arg2);
}

export function ValidateSkills() {
  return window['go']['main']['App']['ValidateSkills']();
}
